"use client";
import { useState } from "react";
import { AIInsight, RiskLevel } from "../lib/types";
import { generateInsight } from "../lib/api";
import { RISK_COLORS, RISK_LABELS } from "../lib/utils";

interface Props { customerId: number }

export default function AIInsightPanel({ customerId }: Props) {
  const [insight, setInsight] = useState<AIInsight | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      const result = await generateInsight(customerId);
      setInsight(result);
    } catch {
      setError("Failed to generate insight. Check the backend.");
    } finally {
      setLoading(false);
    }
  }

  if (!insight && !loading) {
    return (
      <div className="bg-violet-50 border border-violet-200 rounded-xl p-4 text-center">
        <p className="text-sm text-violet-700 font-medium mb-1">AI Risk Assessment</p>
        <p className="text-xs text-violet-500 mb-3">Powered by Claude claude-sonnet-4-6 · Results cached per customer</p>
        <button
          onClick={load}
          className="bg-violet-600 text-white text-sm px-4 py-2 rounded-lg hover:bg-violet-700 transition-colors"
        >
          Generate Insight
        </button>
        {error && <p className="text-xs text-red-500 mt-2">{error}</p>}
      </div>
    );
  }

  if (loading) {
    return (
      <div className="bg-violet-50 border border-violet-200 rounded-xl p-5 text-center">
        <div className="text-violet-500 text-sm animate-pulse">Claude is analyzing this customer...</div>
      </div>
    );
  }

  if (!insight) return null;

  const colors = RISK_COLORS[insight.risk_level as RiskLevel];

  return (
    <div className={`border rounded-xl p-4 ${colors.bg} ${colors.ring} ring-1`}>
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <span className="text-sm font-semibold text-gray-700">AI Risk Assessment</span>
          <span className={`text-xs px-2 py-0.5 rounded-full font-semibold ${colors.bg} ${colors.text} border border-current`}>
            {RISK_LABELS[insight.risk_level as RiskLevel]}
          </span>
        </div>
        <span className="text-xs text-gray-400">{insight.cached ? "Cached" : "Just generated"}</span>
      </div>

      <p className="text-sm text-gray-700 mb-3 leading-relaxed">{insight.summary}</p>

      <div className="space-y-2">
        <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Recommended Actions</p>
        {insight.recommendations.map((rec, i) => (
          <div key={i} className="flex items-start gap-2">
            <span className={`text-xs font-bold mt-0.5 ${colors.text}`}>{i + 1}.</span>
            <p className="text-sm text-gray-700">{rec}</p>
          </div>
        ))}
      </div>

      <p className="text-xs text-gray-400 mt-3">
        Generated by Claude claude-sonnet-4-6 · {new Date(insight.generated_at).toLocaleDateString()}
      </p>
    </div>
  );
}
